### ISSUE TITLE
High latency issue

### ISSUE THREAD

**Issue by DrStegosaurus** [Shadorc/Shadbot#1] opened 2017-11-29 19:02 UTC
Keeps cutting out in the middle of songs, doesn't respond at all at times.

**Comment by Shadorc** [comment] 2017-12-04 20:15
Hello,
I'm aware of this problem, I'm trying to find out the cause but I don't really find yet.
I think it's due to a lack of power from the server on which Shadbot is running but it's not sure.

**Comment by Shadorc** [comment] 2017-12-16 19:30
This should be fixed now

**Closed by Shadorc** 2017-12-16 19:30 UTC
Labels: bug
